https://www.kaggle.com/datasets/soniaaaaaaaa/employment-of-india-cleaned-and-messy-data?select=Messy_Employment_India_Dataset.csv

JOIN IN PANDAS DATAFRAME

In [1]:
import pandas as pd

In [4]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D1.join(D2)

   A  B  C  D
0  1  A  1  a
1  2  B  2  b
2  3  C  3  c
3  4  D  4  d

D2 IS PRIMARY AND D1 IS SECONDARY

In [5]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D2.join(D1)

   C  D  A  B
0  1  a  1  A
1  2  b  2  B
2  3  c  3  C
3  4  d  4  D

INDEX IN JOIN

In [9]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']}, index= ['a','b', 2 , 'd'])
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']})
D1.join(D2)

   A  B    C    D
a  1  A  NaN  NaN
b  2  B  NaN  NaN
2  3  C  3.0    c
d  4  D  NaN  NaN

value of C and D in reverse

In [10]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']}, index= ['a','b', 'c' , 'd'])
D2= pd.DataFrame( { 'C': [1,2,3,4], 'D': ['a','b','c','d']}, index= ['d','c', 'b' , 'a'])
D1.join(D2)

   A  B  C  D
a  1  A  4  d
b  2  B  3  c
c  3  C  2  b
d  4  D  1  a

INNER

In [16]:
D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'inner')

   A   B  C  D
c  3  30  A  E
d  4  40  B  F

OUTER

In [17]:
D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'outer')

   A   B    C    D
a  1  10  NaN  NaN
b  2  20  NaN  NaN
c  3  30    A    E
d  4  40    B    F
e  5  50  NaN  NaN

LEFT

In [18]:
D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'left')

   A   B    C    D
a  1  10  NaN  NaN
b  2  20  NaN  NaN
c  3  30    A    E
d  4  40    B    F
e  5  50  NaN  NaN

RIGHT

In [19]:
D1= pd.DataFrame( { 'A': [1,2,3,4,5], 'B': [10,20,30,40,50]}, index= ['a','b', 'c','d', 'e'])
D2= pd.DataFrame( { 'C': ['A','B'], 'D': ['E', 'F']}, index= ['c','d'])
D1.join(D2, how= 'right')

   A   B  C  D
c  3  30  A  E
d  4  40  B  F

JOINING SAME NAME TABLES

In [24]:
D1= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['A','B','C','D']})
D2= pd.DataFrame( { 'A': [1,2,3,4], 'B': ['a','b','c','d']})
D1.join(D2, lsuffix= '_left', rsuffix= '_right')

   A_left B_left  A_right B_right
0       1      A        1       a
1       2      B        2       b
2       3      C        3       c
3       4      D        4       d